### ISSUE TITLE
Include macro sometimes inserting into wrong index

### ISSUE THREAD

**Issue by Ralakus** [WotScript/WotScript-scanner-preproccessor#4]
The insert macro sometimes inserts into the wrong position if a define macro as been applied and is longer or shorter than the name of the define.

**Comment by Jackojc** [comment]
@Ralakus is this solved?

**Comment by Ralakus** [comment]
I haven't retested it yet

**Comment by Ralakus** [comment]
It's still an issue, I'm planning to do a complete rebuild to remove the modular system since it limits how each macro can interact
